### ISSUE TITLE
Zephyr 86

### ISSUE THREAD

**Issue by svalencia014** [svalencia014/zjx-eats#20]

**Comment by svalencia014** [comment]
Review against SOP

**Comment by jessie846** [comment]
TODO:
- [x] Draw Border
- [x] Draw FPAs
- [x] Update Library
- [x] Play Test

**Comment by svalencia014** [comment]
tested but needs data edits

**Comment by svalencia014** [comment]
Accidentally closed it. Reopening as a reminder to fix shit
