### ISSUE TITLE
Torry 35

### ISSUE THREAD

**Issue by jessie846** [svalencia014/zjx-eats#29]

**Comment by jessie846** [comment]
TODO:
- [x] Draw Border
- [x] Draw FPAs
- [x] Update Library
- [x] Play Test

**Comment by svalencia014** [comment]
works fine

**Comment by svalencia014** [comment]
Add MIT guides for FLL and MIA

**Comment by jessie846** [comment]
no close the issue, i will go back and re add these later, i don't have the energy for this for like 2 weeks
