### ISSUE TITLE
Albany 12

### ISSUE THREAD

**Issue by jessie846** [svalencia014/zjx-eats#41]
TODO:
- [x] Draw Border
- [x] Draw FPAs
- [x] Update Library
- [ ] Play Test

**Comment by svalencia014** [comment]
@jessie846 N callsigns going AYS-ABY go way into ZTL's airspace for some reason

![Image](https://github.com/svalencia014/zjx-eats/assets/68522351/96c09cf9-20a1-48f0-ac80-469b681a787e)

**Comment by jessie846** [comment]
Fixed samva
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh
pluh

**Comment by svalencia014** [comment]
works fine
